### ISSUE TITLE
[FEATURE] Add possibility to download image with all items

### ISSUE THREAD

**Issue by AlexSKuznetsov** [altenull/json-sea#22]
### Describe the feature

Right now when you click on the "Camera" icon downloaded image contains only the viewport items. It will be great if the downloaded image will contain all items.

**Comment by altenull** [comment]
@AlexSKuznetsov 
First of all, I'm terribly sorry for being late.

Actually I had the same thought as you when I put the camera icon (view capture feature).

There were two options for the view capture feature:
1. Capturing the full view **(as you suggested)**
2. Capturing the current view

At that moment, I believed that option `2. Capturing the current view` is more flexible.
(If I had chosen the first option, I wouldn't have been able to cater to users who specifically require the current view)

I recommend using **fit view** in the bottom-right corner of the diagram if you want to capture the full view.
<img width="200" alt="fit view" src="https://github.com/altenull/json-sea/assets/26947777/5028893c-7c28-45a0-b756-7ef1ee479927">

Thanks for your suggestion and I apologize again for the delay.

**Comment by WBDC** [comment]
Hi @altenull , 

I am trying to have a grasp on some google/youtube json structures, etc. 
The json data I try to display is large. I used the top right corner button first and it produced the current view, and the `fit view` button (bottom right) though zoomed out a bit, but the image it produced seems like still what it's currently being displayed. 

![Screenshot 2024-06-03 135801](https://github.com/altenull/json-sea/assets/50083290/912eb63a-9d13-4094-a7a5-83def7f1ba3a)

My screen is 3840x1080. Viewing the fit screen on full screen prompted me a couple of things. 
1. The fit view isn't really a fit view. I think a message about the large object, or even just showing limitations provide the user with information. Lack of this made me do what I normally do... 1 by 1 turning off Ad-blockers, privacy related extensions, all extensions, while refreshing and checking the Devtools console for errors, or any clue for that matter. 
2. Overview not showing when the image is too large. Though this could be in relation with the fit view issue. My best guess is that it unable to fit the view, and the next command (create the overview) didn't run. I did not find/see error message about this.

Just out of curiosity, not being able to create the `fit view` is an unintended bug (e.g. you didn't think some numnuts person would want to view a large dataset) and you just set its limit, or is the limitation coming from elsewhere? 
Speaking out of experience, I am a happy customer when the developer/company behind an app not trying to micromanage with having control over any bit of data. For exampe, I use a chat app (don't want to name it here), and you can type your messages, or send gifs too. Those gifs coming from the same provider. When I use the gifs in another app, it shows 1:1 and I can see the gif in a smaller, but most importantly in full. This chat app I mentioned just banges the gif into a div with the overfloating parts of the image is hidden. When you tap/click on the image will send the gif and not the previewed as you hoped. That particular chat app is a micromenedged app and is more of a monopoly game rather than it's usability or user friendlyness. 

I am not saying your app like this above 👆, because while you gave us something for free, that app is all about $$. My reason to write this as a feedback/suggestion is because I don't want this to fade into "archived" state :)
It is amazing solution. I am very visual type and this makes it a brieze. Well... When I don't try to use that big dataset.
